// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ocg.proto

package rpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Role                 string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content              string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls            []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolExecutionResults []*ToolResult          `protobuf:"bytes,4,rep,name=tool_execution_results,json=toolExecutionResults,proto3" json:"tool_execution_results,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_ocg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolExecutionResults() []*ToolResult {
	if x != nil {
		return x.ToolExecutionResults
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *Function              `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_ocg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_ocg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{2}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ToolFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"` // JSON schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFunction) Reset() {
	*x = ToolFunction{}
	mi := &file_ocg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFunction) ProtoMessage() {}

func (x *ToolFunction) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFunction.ProtoReflect.Descriptor instead.
func (*ToolFunction) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{3}
}

func (x *ToolFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolFunction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolFunction) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *ToolFunction          `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_ocg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{4}
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetFunction() *ToolFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_ocg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{5}
}

func (x *ToolResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChatArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	SessionKey    string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatArgs) Reset() {
	*x = ChatArgs{}
	mi := &file_ocg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatArgs) ProtoMessage() {}

func (x *ChatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatArgs.ProtoReflect.Descriptor instead.
func (*ChatArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{6}
}

func (x *ChatArgs) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatArgs) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type ChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Tools         []*ToolCall            `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_ocg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{7}
}

func (x *ChatReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatReply) GetTools() []*ToolCall {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ChatStreamReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamReply) Reset() {
	*x = ChatStreamReply{}
	mi := &file_ocg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamReply) ProtoMessage() {}

func (x *ChatStreamReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamReply.ProtoReflect.Descriptor instead.
func (*ChatStreamReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{8}
}

func (x *ChatStreamReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type StatsArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsArgs) Reset() {
	*x = StatsArgs{}
	mi := &file_ocg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsArgs) ProtoMessage() {}

func (x *StatsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsArgs.ProtoReflect.Descriptor instead.
func (*StatsArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{9}
}

type StatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         map[string]int32       `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsReply) Reset() {
	*x = StatsReply{}
	mi := &file_ocg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReply) ProtoMessage() {}

func (x *StatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReply.ProtoReflect.Descriptor instead.
func (*StatsReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{10}
}

func (x *StatsReply) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SessionsArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsArgs) Reset() {
	*x = SessionsArgs{}
	mi := &file_ocg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsArgs) ProtoMessage() {}

func (x *SessionsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsArgs.ProtoReflect.Descriptor instead.
func (*SessionsArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{11}
}

func (x *SessionsArgs) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SessionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsReply) Reset() {
	*x = SessionsReply{}
	mi := &file_ocg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsReply) ProtoMessage() {}

func (x *SessionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsReply.ProtoReflect.Descriptor instead.
func (*SessionsReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{12}
}

func (x *SessionsReply) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SessionsReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SessionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionKey      string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	TotalTokens     int32                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CompactionCount int32                  `protobuf:"varint,3,opt,name=compaction_count,json=compactionCount,proto3" json:"compaction_count,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_ocg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{13}
}

func (x *SessionInfo) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *SessionInfo) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *SessionInfo) GetCompactionCount() int32 {
	if x != nil {
		return x.CompactionCount
	}
	return 0
}

func (x *SessionInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MemorySearchArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	MinScore      float32                `protobuf:"fixed32,4,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchArgs) Reset() {
	*x = MemorySearchArgs{}
	mi := &file_ocg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchArgs) ProtoMessage() {}

func (x *MemorySearchArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchArgs.ProtoReflect.Descriptor instead.
func (*MemorySearchArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{14}
}

func (x *MemorySearchArgs) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MemorySearchArgs) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MemorySearchArgs) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MemorySearchArgs) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type MemoryGetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryGetArgs) Reset() {
	*x = MemoryGetArgs{}
	mi := &file_ocg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryGetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryGetArgs) ProtoMessage() {}

func (x *MemoryGetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryGetArgs.ProtoReflect.Descriptor instead.
func (*MemoryGetArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{15}
}

func (x *MemoryGetArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MemoryStoreArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Importance    float32                `protobuf:"fixed32,3,opt,name=importance,proto3" json:"importance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStoreArgs) Reset() {
	*x = MemoryStoreArgs{}
	mi := &file_ocg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStoreArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStoreArgs) ProtoMessage() {}

func (x *MemoryStoreArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStoreArgs.ProtoReflect.Descriptor instead.
func (*MemoryStoreArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{16}
}

func (x *MemoryStoreArgs) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MemoryStoreArgs) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MemoryStoreArgs) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

type ToolResultReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultReply) Reset() {
	*x = ToolResultReply{}
	mi := &file_ocg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultReply) ProtoMessage() {}

func (x *ToolResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultReply.ProtoReflect.Descriptor instead.
func (*ToolResultReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{17}
}

func (x *ToolResultReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type PulseArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseArgs) Reset() {
	*x = PulseArgs{}
	mi := &file_ocg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseArgs) ProtoMessage() {}

func (x *PulseArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseArgs.ProtoReflect.Descriptor instead.
func (*PulseArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{18}
}

func (x *PulseArgs) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PulseArgs) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PulseArgs) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PulseArgs) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PulseArgs) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PulseArgs) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PulseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseReply) Reset() {
	*x = PulseReply{}
	mi := &file_ocg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseReply) ProtoMessage() {}

func (x *PulseReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseReply.ProtoReflect.Descriptor instead.
func (*PulseReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{19}
}

func (x *PulseReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PulseReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *PulseReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AudioArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioArgs) Reset() {
	*x = AudioArgs{}
	mi := &file_ocg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioArgs) ProtoMessage() {}

func (x *AudioArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioArgs.ProtoReflect.Descriptor instead.
func (*AudioArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{20}
}

func (x *AudioArgs) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type AudioChunkArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunkArgs) Reset() {
	*x = AudioChunkArgs{}
	mi := &file_ocg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunkArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunkArgs) ProtoMessage() {}

func (x *AudioChunkArgs) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunkArgs.ProtoReflect.Descriptor instead.
func (*AudioChunkArgs) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{21}
}

func (x *AudioChunkArgs) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *AudioChunkArgs) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type AudioReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioReply) Reset() {
	*x = AudioReply{}
	mi := &file_ocg_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioReply) ProtoMessage() {}

func (x *AudioReply) ProtoReflect() protoreflect.Message {
	mi := &file_ocg_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioReply.ProtoReflect.Descriptor instead.
func (*AudioReply) Descriptor() ([]byte, []int) {
	return file_ocg_proto_rawDescGZIP(), []int{22}
}

func (x *AudioReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ocg_proto protoreflect.FileDescriptor

const file_ocg_proto_rawDesc = "" +
	"\n" +
	"\tocg.proto\x12\x03ocg\"\xac\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\r.ocg.ToolCallR\ttoolCalls\x12E\n" +
	"\x16tool_execution_results\x18\x04 \x03(\v2\x0f.ocg.ToolResultR\x14toolExecutionResults\"Y\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12)\n" +
	"\bfunction\x18\x03 \x01(\v2\r.ocg.FunctionR\bfunction\"<\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"d\n" +
	"\fToolFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\"k\n" +
	"\x04Tool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\bfunction\x18\x02 \x01(\v2\x11.ocg.ToolFunctionR\bfunction\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"H\n" +
	"\n" +
	"ToolResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"U\n" +
	"\bChatArgs\x12(\n" +
	"\bmessages\x18\x01 \x03(\v2\f.ocg.MessageR\bmessages\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\"J\n" +
	"\tChatReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\x05tools\x18\x02 \x03(\v2\r.ocg.ToolCallR\x05tools\"?\n" +
	"\x0fChatStreamReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"\v\n" +
	"\tStatsArgs\"x\n" +
	"\n" +
	"StatsReply\x120\n" +
	"\x05stats\x18\x01 \x03(\v2\x1a.ocg.StatsReply.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"$\n" +
	"\fSessionsArgs\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"S\n" +
	"\rSessionsReply\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.ocg.SessionInfoR\bsessions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x9b\x01\n" +
	"\vSessionInfo\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x05R\vtotalTokens\x12)\n" +
	"\x10compaction_count\x18\x03 \x01(\x05R\x0fcompactionCount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"w\n" +
	"\x10MemorySearchArgs\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tmin_score\x18\x04 \x01(\x02R\bminScore\"#\n" +
	"\rMemoryGetArgs\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"a\n" +
	"\x0fMemoryStoreArgs\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"importance\x18\x03 \x01(\x02R\n" +
	"importance\")\n" +
	"\x0fToolResultReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x9f\x01\n" +
	"\tPulseArgs\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"W\n" +
	"\n" +
	"PulseReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\",\n" +
	"\tAudioArgs\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"P\n" +
	"\x0eAudioChunkArgs\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\"\"\n" +
	"\n" +
	"AudioReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xb7\x04\n" +
	"\x05Agent\x12%\n" +
	"\x04Chat\x12\r.ocg.ChatArgs\x1a\x0e.ocg.ChatReply\x123\n" +
	"\n" +
	"ChatStream\x12\r.ocg.ChatArgs\x1a\x14.ocg.ChatStreamReply0\x01\x12(\n" +
	"\x05Stats\x12\x0e.ocg.StatsArgs\x1a\x0f.ocg.StatsReply\x121\n" +
	"\bSessions\x12\x11.ocg.SessionsArgs\x1a\x12.ocg.SessionsReply\x12;\n" +
	"\fMemorySearch\x12\x15.ocg.MemorySearchArgs\x1a\x14.ocg.ToolResultReply\x125\n" +
	"\tMemoryGet\x12\x12.ocg.MemoryGetArgs\x1a\x14.ocg.ToolResultReply\x129\n" +
	"\vMemoryStore\x12\x14.ocg.MemoryStoreArgs\x1a\x14.ocg.ToolResultReply\x12+\n" +
	"\bPulseAdd\x12\x0e.ocg.PulseArgs\x1a\x0f.ocg.PulseReply\x12.\n" +
	"\vPulseStatus\x12\x0e.ocg.PulseArgs\x1a\x0f.ocg.PulseReply\x126\n" +
	"\x0eSendAudioChunk\x12\x13.ocg.AudioChunkArgs\x1a\x0f.ocg.AudioReply\x121\n" +
	"\x0eEndAudioStream\x12\x0e.ocg.AudioArgs\x1a\x0f.ocg.AudioReplyB&Z$github.com/gliderlab/cogate/rpcprotob\x06proto3"

var (
	file_ocg_proto_rawDescOnce sync.Once
	file_ocg_proto_rawDescData []byte
)

func file_ocg_proto_rawDescGZIP() []byte {
	file_ocg_proto_rawDescOnce.Do(func() {
		file_ocg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocg_proto_rawDesc), len(file_ocg_proto_rawDesc)))
	})
	return file_ocg_proto_rawDescData
}

var file_ocg_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_ocg_proto_goTypes = []any{
	(*Message)(nil),          // 0: ocg.Message
	(*ToolCall)(nil),         // 1: ocg.ToolCall
	(*Function)(nil),         // 2: ocg.Function
	(*ToolFunction)(nil),     // 3: ocg.ToolFunction
	(*Tool)(nil),             // 4: ocg.Tool
	(*ToolResult)(nil),       // 5: ocg.ToolResult
	(*ChatArgs)(nil),         // 6: ocg.ChatArgs
	(*ChatReply)(nil),        // 7: ocg.ChatReply
	(*ChatStreamReply)(nil),  // 8: ocg.ChatStreamReply
	(*StatsArgs)(nil),        // 9: ocg.StatsArgs
	(*StatsReply)(nil),       // 10: ocg.StatsReply
	(*SessionsArgs)(nil),     // 11: ocg.SessionsArgs
	(*SessionsReply)(nil),    // 12: ocg.SessionsReply
	(*SessionInfo)(nil),      // 13: ocg.SessionInfo
	(*MemorySearchArgs)(nil), // 14: ocg.MemorySearchArgs
	(*MemoryGetArgs)(nil),    // 15: ocg.MemoryGetArgs
	(*MemoryStoreArgs)(nil),  // 16: ocg.MemoryStoreArgs
	(*ToolResultReply)(nil),  // 17: ocg.ToolResultReply
	(*PulseArgs)(nil),        // 18: ocg.PulseArgs
	(*PulseReply)(nil),       // 19: ocg.PulseReply
	(*AudioArgs)(nil),        // 20: ocg.AudioArgs
	(*AudioChunkArgs)(nil),   // 21: ocg.AudioChunkArgs
	(*AudioReply)(nil),       // 22: ocg.AudioReply
	nil,                      // 23: ocg.StatsReply.StatsEntry
}
var file_ocg_proto_depIdxs = []int32{
	1,  // 0: ocg.Message.tool_calls:type_name -> ocg.ToolCall
	5,  // 1: ocg.Message.tool_execution_results:type_name -> ocg.ToolResult
	2,  // 2: ocg.ToolCall.function:type_name -> ocg.Function
	3,  // 3: ocg.Tool.function:type_name -> ocg.ToolFunction
	0,  // 4: ocg.ChatArgs.messages:type_name -> ocg.Message
	1,  // 5: ocg.ChatReply.tools:type_name -> ocg.ToolCall
	23, // 6: ocg.StatsReply.stats:type_name -> ocg.StatsReply.StatsEntry
	13, // 7: ocg.SessionsReply.sessions:type_name -> ocg.SessionInfo
	6,  // 8: ocg.Agent.Chat:input_type -> ocg.ChatArgs
	6,  // 9: ocg.Agent.ChatStream:input_type -> ocg.ChatArgs
	9,  // 10: ocg.Agent.Stats:input_type -> ocg.StatsArgs
	11, // 11: ocg.Agent.Sessions:input_type -> ocg.SessionsArgs
	14, // 12: ocg.Agent.MemorySearch:input_type -> ocg.MemorySearchArgs
	15, // 13: ocg.Agent.MemoryGet:input_type -> ocg.MemoryGetArgs
	16, // 14: ocg.Agent.MemoryStore:input_type -> ocg.MemoryStoreArgs
	18, // 15: ocg.Agent.PulseAdd:input_type -> ocg.PulseArgs
	18, // 16: ocg.Agent.PulseStatus:input_type -> ocg.PulseArgs
	21, // 17: ocg.Agent.SendAudioChunk:input_type -> ocg.AudioChunkArgs
	20, // 18: ocg.Agent.EndAudioStream:input_type -> ocg.AudioArgs
	7,  // 19: ocg.Agent.Chat:output_type -> ocg.ChatReply
	8,  // 20: ocg.Agent.ChatStream:output_type -> ocg.ChatStreamReply
	10, // 21: ocg.Agent.Stats:output_type -> ocg.StatsReply
	12, // 22: ocg.Agent.Sessions:output_type -> ocg.SessionsReply
	17, // 23: ocg.Agent.MemorySearch:output_type -> ocg.ToolResultReply
	17, // 24: ocg.Agent.MemoryGet:output_type -> ocg.ToolResultReply
	17, // 25: ocg.Agent.MemoryStore:output_type -> ocg.ToolResultReply
	19, // 26: ocg.Agent.PulseAdd:output_type -> ocg.PulseReply
	19, // 27: ocg.Agent.PulseStatus:output_type -> ocg.PulseReply
	22, // 28: ocg.Agent.SendAudioChunk:output_type -> ocg.AudioReply
	22, // 29: ocg.Agent.EndAudioStream:output_type -> ocg.AudioReply
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ocg_proto_init() }
func file_ocg_proto_init() {
	if File_ocg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocg_proto_rawDesc), len(file_ocg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocg_proto_goTypes,
		DependencyIndexes: file_ocg_proto_depIdxs,
		MessageInfos:      file_ocg_proto_msgTypes,
	}.Build()
	File_ocg_proto = out.File
	file_ocg_proto_goTypes = nil
	file_ocg_proto_depIdxs = nil
}
