// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: ocg.proto

package rpcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_Chat_FullMethodName           = "/ocg.Agent/Chat"
	Agent_ChatStream_FullMethodName     = "/ocg.Agent/ChatStream"
	Agent_Stats_FullMethodName          = "/ocg.Agent/Stats"
	Agent_Sessions_FullMethodName       = "/ocg.Agent/Sessions"
	Agent_MemorySearch_FullMethodName   = "/ocg.Agent/MemorySearch"
	Agent_MemoryGet_FullMethodName      = "/ocg.Agent/MemoryGet"
	Agent_MemoryStore_FullMethodName    = "/ocg.Agent/MemoryStore"
	Agent_PulseAdd_FullMethodName       = "/ocg.Agent/PulseAdd"
	Agent_PulseStatus_FullMethodName    = "/ocg.Agent/PulseStatus"
	Agent_SendAudioChunk_FullMethodName = "/ocg.Agent/SendAudioChunk"
	Agent_EndAudioStream_FullMethodName = "/ocg.Agent/EndAudioStream"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	Chat(ctx context.Context, in *ChatArgs, opts ...grpc.CallOption) (*ChatReply, error)
	ChatStream(ctx context.Context, in *ChatArgs, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamReply], error)
	Stats(ctx context.Context, in *StatsArgs, opts ...grpc.CallOption) (*StatsReply, error)
	Sessions(ctx context.Context, in *SessionsArgs, opts ...grpc.CallOption) (*SessionsReply, error)
	MemorySearch(ctx context.Context, in *MemorySearchArgs, opts ...grpc.CallOption) (*ToolResultReply, error)
	MemoryGet(ctx context.Context, in *MemoryGetArgs, opts ...grpc.CallOption) (*ToolResultReply, error)
	MemoryStore(ctx context.Context, in *MemoryStoreArgs, opts ...grpc.CallOption) (*ToolResultReply, error)
	PulseAdd(ctx context.Context, in *PulseArgs, opts ...grpc.CallOption) (*PulseReply, error)
	PulseStatus(ctx context.Context, in *PulseArgs, opts ...grpc.CallOption) (*PulseReply, error)
	// Audio streaming
	SendAudioChunk(ctx context.Context, in *AudioChunkArgs, opts ...grpc.CallOption) (*AudioReply, error)
	EndAudioStream(ctx context.Context, in *AudioArgs, opts ...grpc.CallOption) (*AudioReply, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Chat(ctx context.Context, in *ChatArgs, opts ...grpc.CallOption) (*ChatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatReply)
	err := c.cc.Invoke(ctx, Agent_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ChatStream(ctx context.Context, in *ChatArgs, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatArgs, ChatStreamReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamReply]

func (c *agentClient) Stats(ctx context.Context, in *StatsArgs, opts ...grpc.CallOption) (*StatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsReply)
	err := c.cc.Invoke(ctx, Agent_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Sessions(ctx context.Context, in *SessionsArgs, opts ...grpc.CallOption) (*SessionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionsReply)
	err := c.cc.Invoke(ctx, Agent_Sessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) MemorySearch(ctx context.Context, in *MemorySearchArgs, opts ...grpc.CallOption) (*ToolResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResultReply)
	err := c.cc.Invoke(ctx, Agent_MemorySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) MemoryGet(ctx context.Context, in *MemoryGetArgs, opts ...grpc.CallOption) (*ToolResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResultReply)
	err := c.cc.Invoke(ctx, Agent_MemoryGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) MemoryStore(ctx context.Context, in *MemoryStoreArgs, opts ...grpc.CallOption) (*ToolResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResultReply)
	err := c.cc.Invoke(ctx, Agent_MemoryStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PulseAdd(ctx context.Context, in *PulseArgs, opts ...grpc.CallOption) (*PulseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PulseReply)
	err := c.cc.Invoke(ctx, Agent_PulseAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PulseStatus(ctx context.Context, in *PulseArgs, opts ...grpc.CallOption) (*PulseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PulseReply)
	err := c.cc.Invoke(ctx, Agent_PulseStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SendAudioChunk(ctx context.Context, in *AudioChunkArgs, opts ...grpc.CallOption) (*AudioReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioReply)
	err := c.cc.Invoke(ctx, Agent_SendAudioChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EndAudioStream(ctx context.Context, in *AudioArgs, opts ...grpc.CallOption) (*AudioReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioReply)
	err := c.cc.Invoke(ctx, Agent_EndAudioStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	Chat(context.Context, *ChatArgs) (*ChatReply, error)
	ChatStream(*ChatArgs, grpc.ServerStreamingServer[ChatStreamReply]) error
	Stats(context.Context, *StatsArgs) (*StatsReply, error)
	Sessions(context.Context, *SessionsArgs) (*SessionsReply, error)
	MemorySearch(context.Context, *MemorySearchArgs) (*ToolResultReply, error)
	MemoryGet(context.Context, *MemoryGetArgs) (*ToolResultReply, error)
	MemoryStore(context.Context, *MemoryStoreArgs) (*ToolResultReply, error)
	PulseAdd(context.Context, *PulseArgs) (*PulseReply, error)
	PulseStatus(context.Context, *PulseArgs) (*PulseReply, error)
	// Audio streaming
	SendAudioChunk(context.Context, *AudioChunkArgs) (*AudioReply, error)
	EndAudioStream(context.Context, *AudioArgs) (*AudioReply, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Chat(context.Context, *ChatArgs) (*ChatReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentServer) ChatStream(*ChatArgs, grpc.ServerStreamingServer[ChatStreamReply]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAgentServer) Stats(context.Context, *StatsArgs) (*StatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedAgentServer) Sessions(context.Context, *SessionsArgs) (*SessionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Sessions not implemented")
}
func (UnimplementedAgentServer) MemorySearch(context.Context, *MemorySearchArgs) (*ToolResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MemorySearch not implemented")
}
func (UnimplementedAgentServer) MemoryGet(context.Context, *MemoryGetArgs) (*ToolResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryGet not implemented")
}
func (UnimplementedAgentServer) MemoryStore(context.Context, *MemoryStoreArgs) (*ToolResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryStore not implemented")
}
func (UnimplementedAgentServer) PulseAdd(context.Context, *PulseArgs) (*PulseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PulseAdd not implemented")
}
func (UnimplementedAgentServer) PulseStatus(context.Context, *PulseArgs) (*PulseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PulseStatus not implemented")
}
func (UnimplementedAgentServer) SendAudioChunk(context.Context, *AudioChunkArgs) (*AudioReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAudioChunk not implemented")
}
func (UnimplementedAgentServer) EndAudioStream(context.Context, *AudioArgs) (*AudioReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EndAudioStream not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Chat(ctx, req.(*ChatArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).ChatStream(m, &grpc.GenericServerStream[ChatArgs, ChatStreamReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamReply]

func _Agent_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stats(ctx, req.(*StatsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Sessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Sessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Sessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Sessions(ctx, req.(*SessionsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_MemorySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemorySearchArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).MemorySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_MemorySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).MemorySearch(ctx, req.(*MemorySearchArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_MemoryGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).MemoryGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_MemoryGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).MemoryGet(ctx, req.(*MemoryGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_MemoryStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryStoreArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).MemoryStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_MemoryStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).MemoryStore(ctx, req.(*MemoryStoreArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PulseAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PulseArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PulseAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PulseAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PulseAdd(ctx, req.(*PulseArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PulseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PulseArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PulseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PulseStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PulseStatus(ctx, req.(*PulseArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SendAudioChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioChunkArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SendAudioChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SendAudioChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SendAudioChunk(ctx, req.(*AudioChunkArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EndAudioStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EndAudioStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EndAudioStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EndAudioStream(ctx, req.(*AudioArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocg.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Agent_Chat_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Agent_Stats_Handler,
		},
		{
			MethodName: "Sessions",
			Handler:    _Agent_Sessions_Handler,
		},
		{
			MethodName: "MemorySearch",
			Handler:    _Agent_MemorySearch_Handler,
		},
		{
			MethodName: "MemoryGet",
			Handler:    _Agent_MemoryGet_Handler,
		},
		{
			MethodName: "MemoryStore",
			Handler:    _Agent_MemoryStore_Handler,
		},
		{
			MethodName: "PulseAdd",
			Handler:    _Agent_PulseAdd_Handler,
		},
		{
			MethodName: "PulseStatus",
			Handler:    _Agent_PulseStatus_Handler,
		},
		{
			MethodName: "SendAudioChunk",
			Handler:    _Agent_SendAudioChunk_Handler,
		},
		{
			MethodName: "EndAudioStream",
			Handler:    _Agent_EndAudioStream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _Agent_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ocg.proto",
}
