version: "2"

linters:
  disable-all: true
  enable:
    - staticcheck
    - ineffassign
    - unused
    - govet
  disable:
    - errcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
